services:
  python:
    image: ${COMPOSE_PROJECT_NAME}:latest
    build:
      context: .
      target: development
    environment:
      GITHUB_WORKSPACE: /usr/src/${COMPOSE_PROJECT_NAME}/
      GITHUB_STEP_SUMMARY: /usr/src/${COMPOSE_PROJECT_NAME}/github-step-summary.md
      DEBUG: false
      RUNNER_DEBUG: true
    tty: true
    volumes:
      - ./:/usr/src/${COMPOSE_PROJECT_NAME}/
  blackd:
    image: pyfound/black:latest_release
    command: blackd --bind-host 0.0.0.0
    ports:
      - "45484:45484"
