name: Formatting and Linting
on: push
jobs:
  formatting-and-linting:
    name: Formatting and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Install Packages
        run: |
          python3 -m pip install --upgrade pip poetry
          poetry install
      - name: Run Black
        uses: psf/black@stable
      - name: Run isort
        uses: isort/isort-action@v1
      - name: Run mypy
        run: mypy
      - name: Run Flake8
        uses: py-actions/flake8@v2
      - name: Run Pylint
        run: pylint .
      - name: Run Ruff
        uses: astral-sh/ruff-action@v1
      - name: Run pytest
        run: pytest --cov=chktex_action
